# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7e02d268fc525fdd8c8aac211fb67026f56aba06bcff51714c24ff8d0fd9a52c7057a1ac62d0cfa44d48c04b4513eb311b9b6ec007fca44322820e864b8da52

test:
  secret_key_base: ea5530988ad141f997fd384a52cd8d8fb9c5e6ea46a07b0e120dc118e9a5b7ec28ad5a49e308cb967d1d401fe5301d7664f34daeb60d5b052cd9d84c77314838

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
